// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzeuCr7wk1z0e4xesIhj7FdUyTwRf4kP4',
    appId: '1:461434572547:web:1e277ce35e419dbaa42336',
    messagingSenderId: '461434572547',
    projectId: 'psantren-asad',
    authDomain: 'psantren-asad.firebaseapp.com',
    storageBucket: 'psantren-asad.firebasestorage.app',
    measurementId: 'G-1YLB0CY51P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5foEaxnOuSxBn13ae0_YJPHDmf_gMPI',
    appId: '1:461434572547:android:678c1146d8ff1596a42336',
    messagingSenderId: '461434572547',
    projectId: 'psantren-asad',
    storageBucket: 'psantren-asad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvT-dk2xENcOCxZ0Z4hzwL77YLyRyiCCk',
    appId: '1:461434572547:ios:07d724233fcb7b9ba42336',
    messagingSenderId: '461434572547',
    projectId: 'psantren-asad',
    storageBucket: 'psantren-asad.firebasestorage.app',
    iosBundleId: 'com.example.pesantrenAsad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvT-dk2xENcOCxZ0Z4hzwL77YLyRyiCCk',
    appId: '1:461434572547:ios:07d724233fcb7b9ba42336',
    messagingSenderId: '461434572547',
    projectId: 'psantren-asad',
    storageBucket: 'psantren-asad.firebasestorage.app',
    iosBundleId: 'com.example.pesantrenAsad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzeuCr7wk1z0e4xesIhj7FdUyTwRf4kP4',
    appId: '1:461434572547:web:96ecb1ab76bf31a7a42336',
    messagingSenderId: '461434572547',
    projectId: 'psantren-asad',
    authDomain: 'psantren-asad.firebaseapp.com',
    storageBucket: 'psantren-asad.firebasestorage.app',
    measurementId: 'G-PCNYYQFX6M',
  );
}
